{{- if include "nriKubernetes.controlPlane.serviceAccount" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with (include "newrelic.common.serviceAccount.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
  name: {{ include "nriKubernetes.controlplane.fullname.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
