{{- if .Values.kubelet.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
  name: {{ include "nriKubernetes.kubelet.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  nri-kubernetes.yml: |
    {{- (merge .Values.common.config (include "newrelic.integrationConfigDefaults" . | fromYaml)) | toYaml | nindent 4 }}
    kubelet:
      enabled: true
      {{- if .Values.kubelet.config }}
      {{- toYaml .Values.kubelet.config | nindent 6 }}
      {{- end }}
      {{- if and (include "newrelic.common.gkeAutopilot" .) (not .Values.kubelet.config.schema) }}
      {{- printf "schema: http" | nindent 6 }}
      {{- end }}
      {{- if and (include "newrelic.common.gkeAutopilot" .) (not .Values.kubelet.config.port) }}
      {{- printf "port: 10255" | nindent 6 }}
      {{- end }}
{{- end }}
